-- adm_client
-- INSERT INTO admin.adm_client (type_id, code, name, description) VALUES ('1', 'atser', 'Atser', 'Atser Laboratory');

-- adm_role
INSERT INTO admin.adm_role(code, name, description, version) VALUES ('atser_admin', 'System Administrator', 'This role has full access a all the client functionalities', 0);
INSERT INTO admin.adm_role(code, name, description, version) VALUES ('atser_project_manager', 'Project Manager', 'This role has full access a all the project functionalities', 0);
INSERT INTO admin.adm_role(code, name, description, version) VALUES ('atser_technician', 'System User', 'This role has access to the regular functionalities', 0);

--======================================================
-- adm_user [pass: admin10]
INSERT INTO admin.adm_user(username, password, email, version) VALUES ('atser_admin', '$2a$12$7IX/yRWa91N8gYBm8CCIMuNauIRGYnRf8EQpEIuMi7KQTFRSs7Fni', 'atser@atser.com', 0);
INSERT INTO admin.adm_user(username, password, email, version) VALUES ('mdelabat', '$2a$12$7IX/yRWa91N8gYBm8CCIMuNauIRGYnRf8EQpEIuMi7KQTFRSs7Fni', 'mdelabad@atser.com', 0);
INSERT INTO admin.adm_user(username, password, email, version) VALUES ('mfuentes', '$2a$12$7IX/yRWa91N8gYBm8CCIMuNauIRGYnRf8EQpEIuMi7KQTFRSs7Fni', 'mfuentes@atser.com', 0);

-- adm_authority atser_technician
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_user_administration' AND f.name = 'view' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_technician'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_user_administration' AND f.name = 'edit' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_technician'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_administration' AND f.name = 'view' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_technician'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_administration' AND f.name = 'edit' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_technician'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_administration' AND f.name = 'create' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_technician'), true, 0);

-- adm_authority atser_project_manager
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_user_administration' AND f.name = 'view' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_project_manager'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_user_administration' AND f.name = 'delete' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_project_manager'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_user_administration' AND f.name = 'edit' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_project_manager'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_user_administration' AND f.name = 'create' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_project_manager'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_simple_catalog_administration' AND f.name = 'view' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_project_manager'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_simple_catalog_administration' AND f.name = 'delete' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_project_manager'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_simple_catalog_administration' AND f.name = 'edit' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_project_manager'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_simple_catalog_administration' AND f.name = 'create' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_project_manager'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_administration' AND f.name = 'view' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_project_manager'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_administration' AND f.name = 'delete' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_project_manager'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_administration' AND f.name = 'edit' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_project_manager'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_administration' AND f.name = 'create' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_project_manager'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_type_administration' AND f.name = 'view' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_project_manager'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_type_administration' AND f.name = 'delete' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_project_manager'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_type_administration' AND f.name = 'edit' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_project_manager'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_type_administration' AND f.name = 'create' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_project_manager'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_project_administration' AND f.name = 'view' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_project_manager'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_project_administration' AND f.name = 'edit' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_project_manager'), true, 0);

-- adm_authority atser_admin
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_user_administration' AND f.name = 'view' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_user_administration' AND f.name = 'delete' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_user_administration' AND f.name = 'edit' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_user_administration' AND f.name = 'create' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_simple_catalog_administration' AND f.name = 'view' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_simple_catalog_administration' AND f.name = 'delete' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_simple_catalog_administration' AND f.name = 'edit' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_simple_catalog_administration' AND f.name = 'create' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_functionalities_administration' AND f.name = 'view' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_functionalities_administration' AND f.name = 'delete' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_functionalities_administration' AND f.name = 'edit' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_functionalities_administration' AND f.name = 'create' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_role_administration' AND f.name = 'view' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_role_administration' AND f.name = 'delete' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_role_administration' AND f.name = 'edit' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_role_administration' AND f.name = 'create' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_profile_administration' AND f.name = 'view' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_profile_administration' AND f.name = 'delete' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_profile_administration' AND f.name = 'edit' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_profile_administration' AND f.name = 'create' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_administration' AND f.name = 'view' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_administration' AND f.name = 'delete' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_administration' AND f.name = 'edit' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_administration' AND f.name = 'create' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_type_administration' AND f.name = 'view' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_type_administration' AND f.name = 'delete' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_type_administration' AND f.name = 'edit' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_type_administration' AND f.name = 'create' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_project_administration' AND f.name = 'view' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_project_administration' AND f.name = 'delete' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_project_administration' AND f.name = 'edit' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_project_administration' AND f.name = 'create' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_region_administration' AND f.name = 'view' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_region_administration' AND f.name = 'delete' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_region_administration' AND f.name = 'edit' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_region_administration' AND f.name = 'create' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_client_administration' AND f.name = 'view' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_client_administration' AND f.name = 'edit' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
-------[menu]------------
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_region_frontend' AND f.name = 'list' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_project_frontend' AND f.name = 'list' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_type_frontend' AND f.name = 'list' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_menu_frontend' AND f.name = 'list' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_user_frontend' AND f.name = 'list' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_module_frontend' AND f.name = 'list' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_client_frontend' AND f.name = 'list' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_simple_catalog_frontend' AND f.name = 'list' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);
INSERT INTO admin.adm_authority(functionality_id, role_id, has_right, version) VALUES ((SELECT ID FROM admin.adm_functionality f WHERE f.code = 'fnc_role_frontend' AND f.name = 'list' ), (SELECT ID FROM admin.adm_role r WHERE r.code = 'atser_admin'), true, 0);



-- adm_profile
INSERT INTO admin.adm_profile(client_id, user_id, role_id, version) VALUES ((select id from admin.adm_client where code = 'atser'), (SELECT u.id FROM admin.adm_user u WHERE u.username = 'atser_admin' AND u.deleted = false), (SELECT r.id FROM admin.adm_role r WHERE r.code = 'atser_admin' AND r.deleted = false),0);
INSERT INTO admin.adm_profile(client_id, user_id, role_id, version) VALUES ((select id from admin.adm_client where code = 'atser'), (SELECT u.id FROM admin.adm_user u WHERE u.username = 'mdelabat' AND u.deleted = false), (SELECT r.id FROM admin.adm_role r WHERE r.code = 'atser_project_manager' AND r.deleted = false),0);
INSERT INTO admin.adm_profile(client_id, user_id, role_id, version) VALUES ((select id from admin.adm_client where code = 'atser'), (SELECT u.id FROM admin.adm_user u WHERE u.username = 'mfuentes' AND u.deleted = false), (SELECT r.id FROM admin.adm_role r WHERE r.code = 'atser_technician' AND r.deleted = false),0);