version: '3.7'



services:
  zipkin-service:
    image: openzipkin/zipkin:2.23 
    container_name: zipkin-service   
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - sp-network 
  keycloak:
    image: jboss/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres # <<< This is the address, change it to your external db ip/domain
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      #KEYCLOAK_LOGLEVEL: DEBUG
      #ROOT_LOGLEVEL: DEBUG
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - postgres
  postgres: # Service name 
    image: postgres:14.2
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5433:5432      
  mongo:
    image: mongo:5.0.8
    container_name: mongodb-service   
    mem_limit: 350m
    ports:
      - "27018:27017"
    networks:
      - sp-network   
    environment: 
      - MONGO_INITDB_DATABASE=property
    #  - MONGO_INITDB_ROOT_USERNAME=admin
    #  - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db 
      - mongo-config:/data/configdb      
volumes:
  postgresql-volume:
    driver: local    
  mongo-data:
    driver: local  
  mongo-config:    
networks:
  sp-network:    
#spring-boot:build-image -DskipTests
    